FROM adoptopenjdk/openjdk11:jdk-11.0.19_7-ubuntu-slim

WORKDIR /opt/app

# Copiar los archivos de la aplicación
COPY . .

RUN chmod +x ./gradlew

# Compilar la aplicación
RUN ./gradlew clean build -x test

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "build/libs/user-management-api.jar"]